### PR TITLE
Support our neighbor's project

### PR DESCRIPTION
**Pull request by Cldfire**
A neighbor of ours owns a small square that previously had the text "PJ" in it. He or she has been extremely courteous and respectful in manner towards our project and has requested some help maintaining his or her own small square (see https://www.reddit.com/r/rust/comments/62yv2i/i_made_a_rustacean_pixelart_for_rplace/dfr94h7/).

This PR adds the square in the desired location; in order to improve and maintain our relations with other citizens, I highly recommend that it gets merged (along with the removal of the dino, #5).

After the bot gets support for multiple targets, this should be added as a separate target.

### CODE REVIEW

**Comment by matematikaadit** [comment]
Did the dino image just being added back in this PR?

**Comment by Cldfire** [comment]
I forked the repo in its current state. This PR will have to be resolved against the PR to remove the dino.

**Comment by JustAPerson** [comment]
All for expanding our botnet to adjacent friendly art.

`Nothing to do (for now) - sleeping for 10 seconds` is boring :(

**Comment by matematikaadit** [comment]
Oh, I see.

Also probably should ask them whether the positioning is correct or not (probably give them the direct link to the image [[1]]) so that it wont destroy what they already build.

[1]: https://raw.githubusercontent.com/Cldfire/ruplace-target/d511c705a9f370ab61ab21c0a4cca8e816b3177f/ruplace.png

**Comment by Cldfire** [comment]
I have discussed this with the owner of the art and asked him or her to verify the image. I was very careful with the positioning, I am certain it is correct :)

I also updated it to match his or her most recent plans (second commit).

**Comment by Kimundi** [comment]
Feel free to update this.

**Comment by matematikaadit** [comment]
personally, it seems better if it has white border.

**Comment by Diggsey** [comment]
Added.

**Pull request closed without merging**
