### PR TITLE
remove moz dino

### PR DESCRIPTION
**Pull request by emberian**

### CODE REVIEW

**Comment by ghost** [comment]
Why? Is it a conflict with another project? We could also move it if you want.

**Comment by Cldfire** [comment]
I agree that the dino should be removed. It isn't the prettiest thing in the world and is taking up space that should be ceded to another project.

The remainder of our holdings represent Rust sufficiently, I think we can all agree on that :)

**Comment by ghost** [comment]
I agree, it looks ugly. https://i.imgur.com/JMxhRZJ.png

**Comment by matematikaadit** [comment]
It's probably related to https://www.reddit.com/r/rust/comments/62yv2i/i_made_a_rustacean_pixelart_for_rplace/dfqz1ie/

**Comment by Cldfire** [comment]
Yes, this is indeed to make room for r/drumcorps.

**Comment by awertt** [comment]
Me and people at /r/drumcorps thanks you guys a ton!

**Comment by est31** [comment]
The dino is quite beautiful. It should rather be moved to the right.

**Comment by Kimundi** [comment]
Merging this since I've seen more people for it than against it. :)

**Pull request merged**
